"""Produce documentation/COVERAGE_GAPS.md -- the writing worksheet.

Answers one question: given what the harvest actually contains, which
constructions is the corpus missing, and what should a human write to fill them?
"""

from __future__ import annotations

import json
import pathlib
import re
import sys
from collections import Counter

ROOT = pathlib.Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from stlm.analyze import CONSTRUCTIONS, TARGET_LIKE_REGISTERS as TARGET_LIKE
from stlm.ir import read_jsonl

def main() -> None:
    harvested = read_jsonl(ROOT / "corpus" / "harvested.jsonl")
    human = read_jsonl(ROOT / "corpus" / "human_raw.jsonl")
    # Human strings ARE target-register by construction, so they count toward
    # the target-like pool. That is what makes the P0 rows fill as you write.
    tgt = ([h["text"] for h in harvested if h.get("register") in TARGET_LIKE and h.get("text")]
           + [h["text"] for h in human if h.get("text")])
    alls = [h["text"] for h in harvested if h.get("text")] + [h["text"] for h in human if h.get("text")]
    n_t, n_a = len(tgt) or 1, len(alls) or 1

    lines: list[str] = []
    w = lines.append
    w("# Coverage Gaps — what to write\n")
    w("Generated by `scripts/gap_report.py`. Regenerate after adding strings.\n")
    w(f"Anchored on **{len(alls)} real strings** — {len(tgt)} target-like, "
      f"of which **{len(human)} are hand-written**.\n")
    if human:
        by_author = Counter(h.get("author", "?") for h in human)
        w("Hand-written by: " + " · ".join(f"`{k}` {v}" for k, v in by_author.most_common()) + "\n")
    w("**What this is:** the harvest tells us which constructions real schedule text "
      "actually contains. Where the count is zero or near-zero, either the "
      "construction is genuinely rare *or* the harvest's register cannot see it — "
      "the two look identical in the data and are distinguished in the notes.\n")
    w("**What this is not:** a measurement of the target distribution. Parser test "
      "suites over-represent absolute dates because that is what they test; forum "
      "posts under-represent attendees. Treat every number as directional.\n")
    w("---\n")
    w("## Priority worksheet\n")
    w("| Priority | Construction | Target-like | All harvest | Why it matters |")
    w("|---|---|---|---|---|")

    rows = []
    for pid, label, rx, why, what, _shape in CONSTRUCTIONS:
        ct = sum(1 for t in tgt if rx.search(t))
        ca = sum(1 for t in alls if rx.search(t))
        pt, pa = 100 * ct / n_t, 100 * ca / n_a
        prio = "P0" if pt < 1.0 else "P1" if pt < 5.0 else "P2" if pt < 15.0 else "P3"
        rows.append((prio, pid, label, ct, pt, ca, pa, why, what))

    for prio, pid, label, ct, pt, ca, pa, why, _ in sorted(rows, key=lambda r: (r[0], -r[4])):
        w(f"| **{prio}** | {label} | {ct} ({pt:.1f}%) | {ca} ({pa:.1f}%) | {why} |")

    w("\n`P0` = essentially absent, write these first. `P1` = thin. "
      "`P2` = present but light. `P3` = well covered by the harvest.\n")
    w("---\n")
    w("## What to write, by priority\n")
    for prio in ("P0", "P1", "P2", "P3"):
        group = [r for r in rows if r[0] == prio]
        if not group:
            continue
        w(f"### {prio}\n")
        for _, pid, label, ct, pt, _, _, _, what in sorted(group, key=lambda r: -r[4]):
            w(f"**{label}** — {ct} found ({pt:.1f}%)  ")
            w(f"{what}\n")

    w("---\n")
    w("## Axis cells to spread across\n")
    w("Do not free-write. Fill cells, or you will produce 500 variants of your five "
      "favourite patterns. For each construction above, vary independently:\n")
    w("| Axis | Values |")
    w("|---|---|")
    w("| casing | all-lower · Title · MIXED · ALLCAPS |")
    w("| spacing | `8-12` · `8 - 12` · `8to12` · `mwf8-12nn` |")
    w("| slot order | temporal first · temporal last · temporal split around the title |")
    w("| register | institutional (`MWF 10:45am-11:40am`) · informal · phone shorthand |")
    w("| length | under 20 chars · 20–50 · over 50 |")
    w("| device | typed on phone · typed on keyboard |")

    hb = sorted(len(t.encode("utf-8")) for t in tgt)
    if hb:
        p = lambda q: hb[min(len(hb) - 1, int(len(hb) * q / 100))]
        w(f"\n**Observed length in the harvest (UTF-8 bytes):** "
          f"p50={p(50)} · p90={p(90)} · p99={p(99)} · max={max(hb)}. "
          f"Your strings should span this range, not cluster at the median.\n")

    reg = Counter(h.get("register", "?") for h in harvested)
    w("\n---\n")
    w("## Harvest composition\n")
    w("| Register | n |")
    w("|---|---|")
    for k, v in reg.most_common():
        mark = " **(target-like)**" if k in TARGET_LIKE else ""
        w(f"| {k}{mark} | {v} |")

    path = ROOT / "documentation" / "COVERAGE_GAPS.md"
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {path.relative_to(ROOT)}")
    for prio, _, label, ct, pt, _, _, _, _ in sorted(rows, key=lambda r: (r[0], -r[4])):
        print(f"  {prio}  {label:<45} {ct:>4} ({pt:.1f}%)")


if __name__ == "__main__":
    main()
